/***** Automatically Generated File *****
 * This file is automatically generated from
 * hw06/tmpl/timerH.tmpl by cheetah during the build process
 * 
 * changes will be overwritten
 */
#pragma once
double time_fnc_simplex(double * x, double * c, double * A, double * b, int n, int m);
